![](../docs/banner.png)

# NumPy


## Exercises

### 1.

Import numpy under the alias `np`.

In [1]:
import numpy as np

### 2.

Create the following arrays:

1. Create an array of 5 zeros.
2. Create an array of 10 ones.
3. Create an array of 5 3.141s.
4. Create an array of the integers 1 to 20.
5. Create a 5 x 5 matrix of ones with a dtype `int`.

In [19]:
zero_array=np.zeros(5)
print(zero_array)

one_array=np.ones(10)
print(one_array)

full_array=np.full(5,3.141)
print(full_array)

range_array=np.arange(1,21)
print(range_array)

int_array=np.ones((5,5)).astype(int)
print(int_array)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3.141 3.141 3.141 3.141 3.141]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### 3.

Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [24]:
random_3D = np.random.rand(3,3,3)
print(random_3D)

random_3D.reshape(27)

[[[0.19894635 0.06708275 0.61742867]
  [0.48384111 0.45885522 0.46999907]
  [0.37653197 0.67822384 0.39142133]]

 [[0.71555768 0.55785604 0.81408783]
  [0.53468096 0.76543432 0.50027052]
  [0.22635737 0.15987335 0.68468899]]

 [[0.82914385 0.43746378 0.71359615]
  [0.86707257 0.544434   0.04554354]
  [0.51640016 0.74264693 0.2323746 ]]]


array([0.19894635, 0.06708275, 0.61742867, 0.48384111, 0.45885522,
       0.46999907, 0.37653197, 0.67822384, 0.39142133, 0.71555768,
       0.55785604, 0.81408783, 0.53468096, 0.76543432, 0.50027052,
       0.22635737, 0.15987335, 0.68468899, 0.82914385, 0.43746378,
       0.71359615, 0.86707257, 0.544434  , 0.04554354, 0.51640016,
       0.74264693, 0.2323746 ])

### 4.

Create an array of 20 linearly spaced numbers between 1 and 10.

In [25]:
line_space=np.linspace(1, 10, 20)
print(line_space)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


### 5.

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [28]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


```python
20
```

In [29]:
a[3,4]

20

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [42]:
a[1:,3:]

array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

```python
array([ 6,  7,  8,  9, 10])
```

In [44]:
a[1,:]

array([ 6,  7,  8,  9, 10])

```python
array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```

In [46]:
a[2:4,:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

```python
array([[ 8,  9],
       [13, 14]])
```

In [49]:
a[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

### 6.

Calculate the sum of all the numbers in `a`.

In [52]:
total=a.sum()
print(f"The sum of all the numbers is {total} ")

The sum of all the numbers is 325 


### 7.

Calculate the sum of each row in `a`.

In [53]:
a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

### 8.

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [54]:
a[a > a.mean()]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

### 9.

Find the location of the minimum value in the following array `b`:

In [56]:
np.random.seed(123)
b = np.random.randn(10)
b

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [60]:
np.argmin(b)

6

### 10.

Find the location of the maximum value in the following 2D array `c` (hint: there are many ways to do this question, but a quick search on stackoverflow.com will typically help you find the optimum solution for a problem, for example see [post](https://stackoverflow.com/questions/3584243/get-the-position-of-the-biggest-item-in-a-multi-dimensional-numpy-array)):

In [62]:
np.random.seed(123)
c = np.random.randn(3, 2)
c

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [72]:
location = np.unravel_index(c.argmax(), c.shape)
print(f"location : {location}")

value=c.max()
print(f"Value : {value}")

location : (2, 1)
Value : 1.651436537097151


<hr>
<hr>
<hr>